---
# handlers file for /root/ansible/roles/apache
#
#

- name: start_apache
  service:
    name: "{{ item }}"
    state: started 
    enabled: true
  with_items: "{{ apache_services }}"
- name: restart_apache
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items: "{{ apache_services }}"



